# Generated by Django 5.0.4 on 2025-02-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategory', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaCategory', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEOC', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaEOC', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaMarca', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMI', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaMI', models.DateTimeField(blank=True, default=None, null=True)),
                ('descripcionMI', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaProveedor', models.DateTimeField(blank=True, default=None, null=True)),
                ('demoraPedido', models.IntegerField(blank=True, default=0, null=True)),
                ('costoPorPedido', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubCategory', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaSubCategory', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUnidadMedida', models.CharField(max_length=100)),
                ('fechaHoraBajaUM', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=100, unique=True)),
                ('stockActual', models.IntegerField(default=0)),
                ('stockSeguridad', models.IntegerField(default=0)),
                ('puntoPedido', models.IntegerField(blank=True, default=0, null=True)),
                ('precioArticulo', models.IntegerField(default=0)),
                ('costoAlmacenamiento', models.IntegerField(default=0)),
                ('loteOptimo', models.IntegerField(default=0)),
                ('tiempoEntrePedidos', models.IntegerField(blank=True, default=0, null=True)),
                ('numeroPedidos', models.IntegerField(blank=True, default=0, null=True)),
                ('demandaPredecida', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaHoraBajaArticulo', models.DateTimeField(blank=True, default=None, null=True)),
                ('descripcionArticulo', models.TextField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.category')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.marca')),
                ('proveedor_predefinido', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaApp.proveedor')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='DemandaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('año', models.IntegerField(choices=[(1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050')])),
                ('cantidadDemanda', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_historicas', to='sistemaApp.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='modeloInventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.modeloinventario'),
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadVendida', models.IntegerField(default=1)),
                ('montoTotal', models.IntegerField(default=0)),
                ('fechaHoraVenta', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_venta', to='sistemaApp.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadLote', models.IntegerField(default=1)),
                ('montoTotal', models.IntegerField(default=0)),
                ('fechaHoraCompra', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='sistemaApp.articulo')),
                ('estadoOrdenCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.estadoordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subCategories',
            field=models.ManyToManyField(related_name='categories', to='sistemaApp.subcategory'),
        ),
    ]
