# Generated by Django 5.0.4 on 2024-06-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFamiliaArticulo', models.CharField(max_length=100)),
                ('fechaHoraBajaFA', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=100)),
                ('stockActual', models.IntegerField(default=0)),
                ('stockSeguridad', models.IntegerField(default=0)),
                ('puntoPedido', models.IntegerField(default=0)),
                ('precioArticulo', models.IntegerField(default=0)),
                ('costoAlmacenamiento', models.IntegerField(default=0)),
                ('familiaArticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.familiaarticulo')),
            ],
        ),
    ]
