# Generated by Django 5.0.4 on 2024-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombreArticulo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='familiaarticulo',
            name='nombreFamiliaArticulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
