# Generated by Django 5.0.4 on 2025-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
