# Generated by Django 5.0.4 on 2025-03-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0002_rename_categorias_subcategoria_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraBaja', models.DateTimeField(blank=True, default=None, null=True)),
                ('nombreMedioPago', models.CharField(max_length=100, unique=True)),
                ('descripcionMedioPago', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
