# Generated by Django 5.0.4 on 2024-06-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0002_alter_articulo_nombrearticulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEOC', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaEOC', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMI', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaMI', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=100, unique=True)),
                ('fechaHoraBajaP', models.DateTimeField(blank=True, default=None, null=True)),
                ('demoraPedido', models.IntegerField(blank=True, default=0, null=True)),
                ('costoPorPedido', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='familiaArticulo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.familiaarticulo'),
        ),
        migrations.AlterField(
            model_name='familiaarticulo',
            name='fechaHoraBajaFA',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='familiaarticulo',
            name='familiaArticulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.modeloinventario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadLote', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='sistemaApp.articulo')),
                ('estadoOrdenCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.estadoordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.proveedor')),
            ],
        ),
    ]
