# Generated by Django 5.0.4 on 2025-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0003_subcategory_categories_alter_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subCategories',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='subCategories', to='sistemaApp.category'),
        ),
    ]
