# Generated by Django 5.0.4 on 2025-03-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0003_mediopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='medioPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.mediopago'),
        ),
    ]
