# Generated by Django 5.0.4 on 2024-06-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0003_estadoordencompra_modeloinventario_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiaarticulo',
            old_name='familiaArticulo',
            new_name='modeloInventario',
        ),
    ]
