# Generated by Django 5.0.4 on 2024-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0004_rename_familiaarticulo_familiaarticulo_modeloinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='montoTotal',
            field=models.IntegerField(default=0),
        ),
    ]
