# Generated by Django 5.0.4 on 2025-03-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0004_remove_category_subcategories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='SubCategoria',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombreCategory',
            new_name='nombreCategoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='nombreSubCategory',
            new_name='nombreSubCategoria',
        ),
    ]
