# Generated by Django 5.0.4 on 2025-03-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0005_alter_demandahistorica_año_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='costoAlmacenamiento',
            new_name='costoAlmacenamientoAnual',
        ),
    ]
