# Generated by Django 5.0.4 on 2025-03-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0006_rename_costoalmacenamiento_articulo_costoalmacenamientoanual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='demandaPredecida',
        ),
    ]
