# Generated by Django 5.0.4 on 2024-06-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0006_demandahistorica'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandahistorica',
            name='cantidadDdemanda',
            field=models.IntegerField(default=0),
        ),
    ]
