# Generated by Django 5.0.4 on 2024-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0007_demandahistorica_cantidadddemanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandahistorica',
            old_name='cantidadDdemanda',
            new_name='cantidadDemanda',
        ),
    ]
