# Generated by Django 5.0.4 on 2025-03-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0007_remove_articulo_demandapredecida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='numeroPedidos',
            new_name='numeroPedidosAnual',
        ),
    ]
