# Generated by Django 5.0.4 on 2024-06-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0010_acciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acciones',
            new_name='Accione',
        ),
    ]
