# Generated by Django 5.0.4 on 2024-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0011_rename_acciones_accione'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='demandaPredecida',
            field=models.IntegerField(default=0),
        ),
    ]
